METHOD USED FOR CURRENT RUN unc_deeplabv3_plus_run1_tl_2_td_256_id_448_md_56_sl_20_run1
cuda being used with 1 GPUs!!
wandb: WARNING Calling wandb.run.save without any arguments is deprecated.Changes to attributes are automatically persisted.
Downloading: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth" to /home3/theanhtran/.cache/torch/hub/checkpoints/resnet101-5d3b4d8f.pth





100%|██████████| 170M/170M [00:11<00:00, 15.5MB/s]
Traceback (most recent call last):
  File "/home3/theanhtran/02_subject/Segmentation/SHNET/main.py", line 358, in <module>
    main(args)
  File "/home3/theanhtran/02_subject/Segmentation/SHNET/main.py", line 167, in main
    torch.load("./models/deeplab-resnet.pth.tar")["state_dict"]
  File "/home3/theanhtran/env/anaconda/envs/3.9Segmentation/lib/python3.9/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home3/theanhtran/env/anaconda/envs/3.9Segmentation/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home3/theanhtran/env/anaconda/envs/3.9Segmentation/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './models/deeplab-resnet.pth.tar'